package es.unileon.iso.gpb.vista;

import static es.unileon.iso.gpb.controller.Controller.joinSubject;
import static es.unileon.iso.gpb.controller.Controller.listSubjectHave;
import static es.unileon.iso.gpb.controller.Controller.listSubjectNotHave;
import es.unileon.iso.gpb.modelo.sets.Subject;
import es.unileon.iso.gpb.modelo.users.User;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Roberto
 */
public class SelectSubjects extends javax.swing.JFrame {

    private User user;
    /**
     * Creates new form MyAccount
     */
    public SelectSubjects() {
        this.user=null;
        init();
    }
    public SelectSubjects(User user){
        this.user=user;
        init();
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        notChoosenSubjectsBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yourSubjectsBox = new javax.swing.JComboBox<>();
        leaveSubject = new javax.swing.JButton();
        joinSubject = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("GBP My Account");
        setResizable(false);

        backButton.setText("←");
        backButton.setFocusable(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        Title.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Title.setText("Select Subjects");

        notChoosenSubjectsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subjects" }));

        jLabel6.setText("Not choosen subjects:");

        jLabel7.setText("Your subjects");

        yourSubjectsBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Subjects" }));

        leaveSubject.setText("Leave");
        leaveSubject.setFocusable(false);
        leaveSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveSubjectActionPerformed(evt);
            }
        });

        joinSubject.setText("Join");
        joinSubject.setFocusable(false);
        joinSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinSubjectActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(Title)
                .addContainerGap(100, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(notChoosenSubjectsBox, 0, 152, Short.MAX_VALUE)
                            .addComponent(yourSubjectsBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(leaveSubject)
                            .addComponent(joinSubject)))
                    .addComponent(jLabel7))
                .addGap(51, 51, 51))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(backButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(Title, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(notChoosenSubjectsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(joinSubject))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yourSubjectsBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(leaveSubject))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_backButtonActionPerformed

    private void leaveSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveSubjectActionPerformed
        String subject = String.valueOf(yourSubjectsBox.getSelectedItem());
        
        if(javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to leave "+subject+"?",
                    "Leave subject?",JOptionPane.INFORMATION_MESSAGE) == javax.swing.JOptionPane.YES_OPTION){
            leaveSubject(this.user.getID(),subject);
            loadLists();
        }


    }//GEN-LAST:event_leaveSubjectActionPerformed

    private void joinSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinSubjectActionPerformed
        String subject = String.valueOf(notChoosenSubjectsBox.getSelectedItem());

        if(javax.swing.JOptionPane.showConfirmDialog(this, "Are you sure you want to join "+subject+"?",
                    "Join subject?",JOptionPane.INFORMATION_MESSAGE) == javax.swing.JOptionPane.YES_OPTION){
            joinSubject(this.user.getID(),subject);
            loadLists();
        }
        
        
    }//GEN-LAST:event_joinSubjectActionPerformed
    
    private void init(){
        
        initComponents();
        java.awt.Dimension dim = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2); 
        java.awt.Toolkit t = java.awt.Toolkit.getDefaultToolkit();
        setIconImage(t.getImage(getClass().getResource("./logo.png"))); 
        loadLists();

        
       
    }
    
    private void loadLists(){
        DefaultComboBoxModel<String> model2 = new DefaultComboBoxModel<>( listSubjectHave(this.user.getID()).toArray(new String[0]) );
        yourSubjectsBox.setModel(model2);
        
        DefaultComboBoxModel<String> model1 = new DefaultComboBoxModel<>( listSubjectNotHave(this.user.getID()).toArray(new String[0]) );
        notChoosenSubjectsBox.setModel(model1);  
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Title;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton joinSubject;
    private javax.swing.JButton leaveSubject;
    private javax.swing.JComboBox<String> notChoosenSubjectsBox;
    private javax.swing.JComboBox<String> yourSubjectsBox;
    // End of variables declaration//GEN-END:variables

    private void leaveSubject(String id, String subject) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
